"""Ports — interfaces the application layer depends on (Dependency Inversion).

Infrastructure adapters implement these. Using `typing.Protocol` for structural
typing: adapters need not inherit, they just match the shape. This keeps the
domain free of any infrastructure import.
"""
from __future__ import annotations  # lazy annotations: `list` method won't shadow builtin in hints

from typing import Protocol, Optional, runtime_checkable

from app.domain.entities import AvoidEntry, Example, Profile, Term


@runtime_checkable
class LLMProvider(Protocol):
    """An OpenAI-compatible chat LLM. Returns the assistant message content."""
    def chat(self, messages: list[dict], max_tokens: int = 1024, temperature: float = 0.2) -> str: ...


class TermbaseRepository(Protocol):
    """Storage for termbase entries (file now, AgentBase Memory later)."""
    def match_in(self, source: str) -> list[Term]: ...
    def search(self, query: str = "", status: Optional[str] = None) -> list[Term]: ...
    def upsert(self, term: Term) -> None: ...
    def archive(self, source: str) -> None: ...


class ReviewChannel(Protocol):
    """Destination for drafts needing human review (file queue now, Teams later)."""
    def enqueue(self, job_id: str, payload: dict) -> None: ...


class CorrectionStore(Protocol):
    """Persists wrong→right corrections and retrieves ones relevant to a source."""
    def save(self, source: str, wrong: str, right: str, note: str = "") -> None: ...
    def for_text(self, source: str) -> list[dict]: ...


class ProfileRepository(Protocol):
    """Storage for profiles (Domain Packs). File-backed now, DB later — same port.

    Definition (profile.json) and per-language assets (tone/avoid/examples) live
    together under one namespace; tenant data (termbase/corrections/queue) is wired
    separately by the composition root via profile_paths (Phase 02).
    """
    def get(self, profile_id: str) -> Optional[Profile]: ...
    def list(self) -> list[Profile]: ...
    def exists(self, profile_id: str) -> bool: ...
    def upsert(self, profile: Profile) -> None: ...
    def tone(self, profile_id: str, lang: str) -> str: ...
    def avoid(self, profile_id: str, lang: str) -> list[AvoidEntry]: ...
    def examples(self, profile_id: str, lang: str) -> list[Example]: ...
    def set_tone(self, profile_id: str, lang: str, text: str) -> None: ...
    def set_avoid(self, profile_id: str, lang: str, entries: list[AvoidEntry]) -> None: ...
